# Generated by Django 2.0.3 on 2019-11-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0006_auto_20190507_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estate',
            field=models.CharField(choices=[('valid', 'valid'), ('done', 'done'), ('cancel', 'cancel')], default='valid', max_length=10),
        ),
        migrations.AlterField(
            model_name='others_order',
            name='estate',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=10),
        ),
    ]
